# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design/dialog_location.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LocationDialog(object):
    def setupUi(self, LocationDialog):
        LocationDialog.setObjectName("LocationDialog")
        LocationDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        LocationDialog.resize(250, 86)
        LocationDialog.setMinimumSize(QtCore.QSize(250, 0))
        LocationDialog.setMaximumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setPointSize(10)
        LocationDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/logo-pc.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LocationDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(LocationDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalFrame = QtWidgets.QFrame(LocationDialog)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cb_best_photo = QtWidgets.QCheckBox(self.verticalFrame)
        self.cb_best_photo.setObjectName("cb_best_photo")
        self.verticalLayout_2.addWidget(self.cb_best_photo, 0, QtCore.Qt.AlignHCenter)
        self.btn_location_confirmation = QtWidgets.QPushButton(self.verticalFrame)
        self.btn_location_confirmation.setObjectName("btn_location_confirmation")
        self.verticalLayout_2.addWidget(self.btn_location_confirmation)
        self.verticalLayout.addWidget(self.verticalFrame, 0, QtCore.Qt.AlignTop)

        self.retranslateUi(LocationDialog)
        QtCore.QMetaObject.connectSlotsByName(LocationDialog)

    def retranslateUi(self, LocationDialog):
        _translate = QtCore.QCoreApplication.translate
        LocationDialog.setWindowTitle(_translate("LocationDialog", "Location Dialog"))
        self.cb_best_photo.setText(_translate("LocationDialog", "Best Photo: 0"))
        self.btn_location_confirmation.setText(_translate("LocationDialog", "Location Confirmation"))
import resources_rc
