# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design/dialog_add_count_photos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_photos_count_dialog(object):
    def setupUi(self, add_photos_count_dialog):
        add_photos_count_dialog.setObjectName("add_photos_count_dialog")
        add_photos_count_dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        add_photos_count_dialog.resize(881, 781)
        self.verticalLayout = QtWidgets.QVBoxLayout(add_photos_count_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(add_photos_count_dialog)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_3 = QtWidgets.QSplitter(self.widget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.groupBox = QtWidgets.QGroupBox(self.splitter_3)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.frameDisplayPhoto = QtWidgets.QFrame(self.splitter_2)
        self.frameDisplayPhoto.setMinimumSize(QtCore.QSize(500, 300))
        self.frameDisplayPhoto.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameDisplayPhoto.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDisplayPhoto.setObjectName("frameDisplayPhoto")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frameDisplayPhoto)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.imageLayout = QtWidgets.QGridLayout()
        self.imageLayout.setObjectName("imageLayout")
        self.gridLayout_3.addLayout(self.imageLayout, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.splitter_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter = QtWidgets.QSplitter(self.frame_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.treeView_directories = QtWidgets.QTreeView(self.splitter)
        self.treeView_directories.setObjectName("treeView_directories")
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.splitter_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter_3)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(add_photos_count_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(add_photos_count_dialog)
        self.buttonBox.accepted.connect(add_photos_count_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(add_photos_count_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(add_photos_count_dialog)

    def retranslateUi(self, add_photos_count_dialog):
        _translate = QtCore.QCoreApplication.translate
        add_photos_count_dialog.setWindowTitle(_translate("add_photos_count_dialog", "Add Photos"))
