# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design/dialog_visual_count.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VisualCountDialog(object):
    def setupUi(self, VisualCountDialog):
        VisualCountDialog.setObjectName("VisualCountDialog")
        VisualCountDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        VisualCountDialog.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(VisualCountDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(VisualCountDialog)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_delete = QtWidgets.QPushButton(self.widget)
        self.btn_delete.setMaximumSize(QtCore.QSize(200, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/png/32x32/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete.setIcon(icon)
        self.btn_delete.setObjectName("btn_delete")
        self.gridLayout.addWidget(self.btn_delete, 0, 2, 1, 1)
        self.btn_add = QtWidgets.QPushButton(self.widget)
        self.btn_add.setMaximumSize(QtCore.QSize(200, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/png/32x32/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add.setIcon(icon1)
        self.btn_add.setObjectName("btn_add")
        self.gridLayout.addWidget(self.btn_add, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignLeft)
        self.tableWidget = QtWidgets.QTableWidget(VisualCountDialog)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(VisualCountDialog)
        self.buttonBox.setStyleSheet("")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(VisualCountDialog)
        self.buttonBox.accepted.connect(VisualCountDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(VisualCountDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(VisualCountDialog)

    def retranslateUi(self, VisualCountDialog):
        _translate = QtCore.QCoreApplication.translate
        VisualCountDialog.setWindowTitle(_translate("VisualCountDialog", "Visual Count"))
        self.btn_delete.setText(_translate("VisualCountDialog", "Delete"))
        self.btn_add.setText(_translate("VisualCountDialog", "Add"))
import resources_rc
