# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design/window_count_report.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CountReportWindow(object):
    def setupUi(self, CountReportWindow):
        CountReportWindow.setObjectName("CountReportWindow")
        CountReportWindow.resize(850, 600)
        CountReportWindow.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/png/32x32/diagram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CountReportWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(CountReportWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 25))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignLeft)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout.addWidget(self.tabWidget)
        CountReportWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CountReportWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 21))
        self.menubar.setObjectName("menubar")
        CountReportWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CountReportWindow)
        self.statusbar.setObjectName("statusbar")
        CountReportWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(CountReportWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(250, 64))
        self.dockWidget.setMaximumSize(QtCore.QSize(524287, 524287))
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_options = QtWidgets.QVBoxLayout()
        self.verticalLayout_options.setObjectName("verticalLayout_options")
        self.verticalLayout_2.addLayout(self.verticalLayout_options)
        self.dockWidget.setWidget(self.dockWidgetContents)
        CountReportWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)

        self.retranslateUi(CountReportWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(CountReportWindow)

    def retranslateUi(self, CountReportWindow):
        _translate = QtCore.QCoreApplication.translate
        CountReportWindow.setWindowTitle(_translate("CountReportWindow", "Photo Count Report"))
        self.dockWidget.setWindowTitle(_translate("CountReportWindow", "Options"))
import resources_rc
