# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design/window_animal_id_report.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnimalIdReportWindow(object):
    def setupUi(self, AnimalIdReportWindow):
        AnimalIdReportWindow.setObjectName("AnimalIdReportWindow")
        AnimalIdReportWindow.resize(900, 600)
        AnimalIdReportWindow.setMinimumSize(QtCore.QSize(900, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/png/32x32/diagram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AnimalIdReportWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(AnimalIdReportWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignLeft)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout.addWidget(self.tabWidget)
        AnimalIdReportWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AnimalIdReportWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        AnimalIdReportWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AnimalIdReportWindow)
        self.statusbar.setObjectName("statusbar")
        AnimalIdReportWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(AnimalIdReportWindow)
        self.dockWidget.setMinimumSize(QtCore.QSize(250, 42))
        self.dockWidget.setMaximumSize(QtCore.QSize(524287, 524287))
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_options = QtWidgets.QVBoxLayout()
        self.verticalLayout_options.setObjectName("verticalLayout_options")
        self.verticalLayout_3.addLayout(self.verticalLayout_options)
        self.dockWidget.setWidget(self.dockWidgetContents)
        AnimalIdReportWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)

        self.retranslateUi(AnimalIdReportWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(AnimalIdReportWindow)

    def retranslateUi(self, AnimalIdReportWindow):
        _translate = QtCore.QCoreApplication.translate
        AnimalIdReportWindow.setWindowTitle(_translate("AnimalIdReportWindow", "AnimalId Report"))
        self.dockWidget.setWindowTitle(_translate("AnimalIdReportWindow", "Options"))
import resources_rc
